/*From:>>Has Operating system(OS) like ex:Linux,ubuntu,MS,Alpine(light wt OS)
it is used to define base image fo container
it is mandatory to define the base image*/
//Label:for describing the metadata
//Run:all the sh commands which would be used

FROM:Alpine:latest
LABLE: author="ruchita3107"
RUN:mkdir /j  avaHome
